# fly.toml file generated for ash-hq on 2022-03-29T12:13:43-04:00

app = "ash-hq"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "_build/prod/rel/ash_hq/bin/ash_hq eval 'UAInspector.Downloader.download && UAInspector.reload && AshHq.Release.migrate'"

[env]

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 9000

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
